---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: ubuntu
  
  # Vars: variables that will apply to the play, on all target systems
  vars_files:
    - vars
  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day


    - name: Install Nginx
      package:
        name: nginx
        state: latest
    
    - name: Install Git
      package:
        name: git
        state: latest
    
    - name: Install Npm
      package:
        name: npm
        state: latest
    
    - name: Copy SSH key in servers for github
      copy: 
        src: ~/.ssh/id_rsa
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: 0600

    - name: Clone project in servers
      git:
        repo: git@github.com:alvarolloret/deploy-vue.git
        version: master
        dest: /root/blog/
        accept_hostkey: yes
    
    - name: Install node_modules
      command: npm install
      args:
        chdir: /root/blog/

    - name: Build NPM project
      command: npm run build
      args:
        chdir: /root/blog/
    
    - name: Copy dist in nginx location 
      copy:
        src: /root/blog/dist/
        dest: "{{ nginx_root_location }}"
        remote_src: True
        mode: 7777

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      notify: Check HTTP Service
    
  # Handlers: the list of handlers that are executed as a notify key from a task
  handlers:
    - name: Check HTTP Service
      uri:
        url: http://{{ ansible_default_ipv4.address }}
        status_code: 200 

# Three dots indicate the end of a YAML document
...
